"""add interview params

Revision ID: 78febae655f1
Revises: 31ef3f7a3f37
Create Date: 2026-05-15 22:07:09.867724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78febae655f1'
down_revision: Union[str, Sequence[str], None] = '31ef3f7a3f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_session', sa.Column('vacancy', sa.String(), nullable=True))
    op.add_column('interview_session', sa.Column('level', sa.String(), nullable=True))
    op.add_column('interview_session', sa.Column('language', sa.String(), nullable=True))
    op.add_column('interview_session', sa.Column('question_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_session', 'question_count')
    op.drop_column('interview_session', 'language')
    op.drop_column('interview_session', 'level')
    op.drop_column('interview_session', 'vacancy')
    # ### end Alembic commands ###
